In [24]:
import os
import numpy as np
import pandas as pd;        pd.set_option( 'display.max_rows', None )
from typing import List

In [2]:
df = pd.read_excel(
    '../data/raw/Inv . DKC شهر2-2026 (1).xls',
    sheet_name= 'PT',
    
).iloc[ 9 : 108, 1 : ]

In [3]:
df = df.dropna( how = 'all' )

In [4]:
df.shape

(91, 9)

In [5]:
df.iloc[:, 1:].isna().sum( axis = 1 ).apply( lambda x : x == 8 )

9       True
10     False
11     False
12     False
13     False
15      True
16     False
17     False
18     False
19     False
21      True
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32     False
33     False
34     False
35     False
36     False
37     False
38     False
39     False
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
62      True
63     False
64     False
65     False
66     False
67     False
68     False
71      True
72     False
73     False
74     False
75     False
76     False
77     False
78     False
79     False
80     False
81     False
82     False
83     False
84     False
86      True
87     False
88     False
90      True
91     False
92     False
93     False
94     False
95     False
96     False
97     False
98     False
99     False
100    False
101    False
102    False
103    False
104    False
105    False
106    False
107    False
dtype: bool

In [6]:
df.columns = [ 'النوع', 'البيـــــــــــــــــــــان', 'الكود', 'الامبير', 'مقاس', 'العدد', 'ملاحظـــــات', 'محجوز', 'رصيد بعد الحجز']

In [7]:
df.head()

,النوع,البيـــــــــــــــــــــان,الكود,الامبير,مقاس,العدد,ملاحظـــــات,محجوز,رصيد بعد الحجز
9,نحاس مستورد,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,م,البيـــــــــــــــــــــان,الكود,الامبير,مقاس,العدد,ملاحظـــــات,محجوز,رصيد بعد الحجز
11,1,شريط نحاس مستورد 3 متر,BST 16C,1600,100*5.75,0,NaN,NaN,0
12,2,شريط نحاس مستورد 3 متر,CUB0030,2000,130*5.75,49,NaN,NaN,49
13,3,شريط نحاس مستورد 3 متر,BST 20C,2500,160*5.75,6,NaN,NaN,6

In [8]:
df['النوع'].head(5)

9     نحاس مستورد
10               م
11               1
12               2
13               3
Name: النوع, dtype: object

In [9]:
df['النوع'][9], df['النوع'][11]

('نحاس مستورد ', 1)

In [10]:
df['النوع'] = [ np.nan if type( value ) == int or value == 'م' else value for value in df['النوع'] ]
df['النوع'].unique()

<StringArray>
[           'نحاس مستورد ',                       nan,
 'نحاس مرحل من جرد زوكينى',               'نحاس محلى',
  'نحاس محلى مقاسات جديدة',           'الومنيوم منحس',
   'الومنيوم مستورد مقصدر',               'الومنيوم ']
Length: 8, dtype: str

In [11]:
df['النوع'] = df['النوع'].ffill()

In [12]:
titles_indices = df[ df.iloc[:, 1:].isna().sum( axis = 1 ).apply( lambda x : x == 8 )  ].index
titles_indices

Index([9, 15, 21, 62, 71, 86, 90], dtype='int64')

In [13]:
df.drop( index = titles_indices, inplace = True )
df.reset_index( inplace = True, drop = True )

In [14]:
df['النوع'].value_counts()

النوع
نحاس محلى                  38
الومنيوم                   17
الومنيوم منحس              13
نحاس محلى مقاسات جديدة      6
نحاس مستورد                 4
نحاس مرحل من جرد زوكينى     4
الومنيوم مستورد مقصدر       2
Name: count, dtype: int64

In [15]:
df.iloc[ : ,1: ].head( 30 ).duplicated()

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8      True
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
dtype: bool

In [16]:
titles_indices = df[ df.iloc[ : ,1: ].duplicated() ].index
titles_indices

Index([4, 8, 46, 65, 67], dtype='int64')

In [17]:
df.drop( index = titles_indices, inplace = True )
df.reset_index( inplace = True, drop = True )

In [18]:
df = df.iloc[ 1 :, : ]

In [19]:
df['النوع'].value_counts()

النوع
نحاس محلى                  37
الومنيوم                   16
الومنيوم منحس              13
نحاس محلى مقاسات جديدة      5
نحاس مستورد                 3
نحاس مرحل من جرد زوكينى     3
الومنيوم مستورد مقصدر       1
Name: count, dtype: int64

In [20]:
df.head()

,النوع,البيـــــــــــــــــــــان,الكود,الامبير,مقاس,العدد,ملاحظـــــات,محجوز,رصيد بعد الحجز
1,نحاس مستورد,شريط نحاس مستورد 3 متر,BST 16C,1600,100*5.75,0,NaN,NaN,0
2,نحاس مستورد,شريط نحاس مستورد 3 متر,CUB0030,2000,130*5.75,49,NaN,NaN,49
3,نحاس مستورد,شريط نحاس مستورد 3 متر,BST 20C,2500,160*5.75,6,NaN,NaN,6
4,نحاس مرحل من جرد زوكينى,شريط نحاس مستورد 3 متر,NaN,2000,150*5.25,1,NaN,NaN,1
5,نحاس مرحل من جرد زوكينى,شريط نحاس مستورد 3 متر,NaN,NaN,150*5,51,NaN,NaN,51

In [21]:
df.drop( index = [49], inplace = True )
df.reset_index( inplace = True, drop = True )

### Export the prepared data

In [22]:
os.makedirs( '../data/prepared/PT', exist_ok= True )
df.to_excel('../data/prepared/PT/PT_01.xlsx')