### Importing Libraries

In [1]:
import os
import numpy as np
import pandas as pd;  
import sqlite3
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from wordcloud import WordCloud

In [2]:
conn = sqlite3.connect( 'Stock.db' )
df = pd.read_sql( 'SELECT * FROM PT;', conn )

In [3]:
df

,النوع,البيـــــــــــــــــــــان,الكود,الامبير,مقاس,العدد,ملاحظـــــات,محجوز,رصيد بعد الحجز,متاح
0,نحاس مستورد,شريط نحاس مستورد 3 متر,BST 16C,1600,100*5.75,0,-,-,0,غير متاح
1,نحاس مستورد,شريط نحاس مستورد 3 متر,CUB0030,2000,130*5.75,49,-,-,49,متاح
2,نحاس مستورد,شريط نحاس مستورد 3 متر,BST 20C,2500,160*5.75,6,-,-,6,متاح
3,نحاس مرحل من جرد زوكينى,شريط نحاس مستورد 3 متر,محلى,2000,150*5.25,1,-,-,1,متاح
4,نحاس مرحل من جرد زوكينى,شريط نحاس مستورد 3 متر,محلى,إكسسوارات,150*5,51,-,-,51,متاح
...,...,...,...,...,...,...,...,...,...,...
72,الومنيوم,شريط الومنيوم 3 متر,محلى,إكسسوارات,40*4,20,مقطع,-,20,متاح
73,الومنيوم,شريط الومنيوم 3 متر,محلى,إكسسوارات,40*3.25,148,المقاسات غير دقيقة DT,-,148,متاح
74,الومنيوم,شريط الومنيوم 3 متر,محلى,إكسسوارات,60*4,138,المقاسات غير دقيقة DT,-,138,متاح
75,الومنيوم,شريط الومنيوم 3 متر,محلى,إكسسوارات,60*3.25,111,المقاسات غير دقيقة DT,-,111,متاح
76,الومنيوم,مجموعة الومنيوم مفكوكة من بارات اليكس ويست بار...,محلى,إكسسوارات,60*3.25,0,المقاسات غير دقيقة DT,-,0,غير متاح

# KPIs Section

In [30]:
no_of_unique_conductors_types = len( df )
no_of_types = int( df['النوع'].nunique() )
no_of_stock_items = int( df[ df['متاح'] == 'متاح' ]['العدد'].sum() )


no_of_unique_conductors_types, no_of_types, no_of_stock_items

(77, 7, 5836)

In [4]:
df['العدد'].sum()

np.int64(5836)

In [5]:
no_of_conductor_types = df['النوع'].nunique()

In [6]:
df['مقاس'].nunique()

53

In [7]:
df['مقاس'].nunique()

53

In [23]:
from  plotly.graph_objs._figure import Figure
import plotly.express as px
def apply_figure_layout( fig : Figure, title_text = '', xlabel_text = '', ylabel_text = '' ) -> Figure :
    
    xlabel_text = fig.layout.xaxis.title.text if xlabel_text == '' else xlabel_text
    ylabel_text = fig.layout.yaxis.title.text if ylabel_text == '' else ylabel_text
    title_text = fig.layout.title.text if title_text == '' else title_text  
    
    fig.update_traces(textfont_size=30)
    
    fig.update_layout(
        
        title = dict(
            pad = dict( l = 100 ), xanchor = 'left',
            text = title_text,
            font = dict( family = 'times', size = 30, color = "#0F52BA" )
        ),
        
        xaxis = dict(
            title = dict(
                text = xlabel_text, font = dict( family = 'times', size = 40, color = '#0F52BA' )
            ),
        tickfont =dict( family = 'times', size = 22, color = '#0F52BA' ),
        

        ),    
        yaxis = dict(
            title = dict(
                text = ylabel_text, font = dict( family = 'times', size = 40, color = '#0F52BA' )
            ),
        tickfont =dict( family = 'times', size = 22, color = "#0F52BA" )

        ),
        
        legend = dict(
            bordercolor = "#0F52BA",
            font = dict( family = 'times', size = 27, color = '#0F52BA', lineposition = 'under' )
        ),
        
        hoverlabel = dict(
            font = dict( family = 'times', size = 23.5, color = '#FFFFFF', lineposition = 'under' )
        ),
        
    )  
    
    fig.update_traces(
    textfont=dict(
        family="times", 
        size=28,
        )
    )
    
    return fig

    
    
category_color_map = {
    'medium' : "#5CA0AD",
    'heavy' : "#144180",
    'sitting' : "#3E772B",
    'standing' : "#AF2316"
}

In [26]:
fig =px.sunburst( df, path = [ 'النوع', 'الامبير' ], color = 'النوع', values= 'العدد',  color_discrete_sequence= ['#0F52BA'],
                 height= 600, width = 1200)
fig.update_traces( hovertemplate="<b>%{label}</b><br>العدد=%{value}<extra></extra>" )
fig = apply_figure_layout( fig )
fig

In [27]:
fig =px.treemap( df, path = [ 'النوع', 'الامبير' ], color = 'النوع', values= 'العدد',  color_discrete_sequence= ['#0F52BA'],
                 height= 600, width = 1200)
fig = apply_figure_layout( fig )
fig

In [28]:
df.head(1)

,النوع,البيـــــــــــــــــــــان,الكود,الامبير,مقاس,العدد,ملاحظـــــات,محجوز,رصيد بعد الحجز,متاح
0,نحاس مستورد,شريط نحاس مستورد 3 متر,BST 16C,1600,100*5.75,0,-,-,0,غير متاح

In [29]:
fig2 = px.histogram( df, x = 'النوع', template= 'simple_white', text_auto=True, color = 'متاح',
                    barmode= 'stack', color_discrete_map= { 'متاح' : '#0F52BA', 'غير متاح' : '#A6C5D7'  })
fig.update_traces(
    hovertemplate="<b>%{x}</b><br>العدد: %{y}<extra></extra>"
)
fig2 = apply_figure_layout( fig2, ylabel_text= 'التعداد' )
fig2

<hr>

In [31]:
df

,النوع,البيـــــــــــــــــــــان,الكود,الامبير,مقاس,العدد,ملاحظـــــات,محجوز,رصيد بعد الحجز,متاح
0,نحاس مستورد,شريط نحاس مستورد 3 متر,BST 16C,1600,100*5.75,0,-,-,0,غير متاح
1,نحاس مستورد,شريط نحاس مستورد 3 متر,CUB0030,2000,130*5.75,49,-,-,49,متاح
2,نحاس مستورد,شريط نحاس مستورد 3 متر,BST 20C,2500,160*5.75,6,-,-,6,متاح
3,نحاس مرحل من جرد زوكينى,شريط نحاس مستورد 3 متر,محلى,2000,150*5.25,1,-,-,1,متاح
4,نحاس مرحل من جرد زوكينى,شريط نحاس مستورد 3 متر,محلى,إكسسوارات,150*5,51,-,-,51,متاح
...,...,...,...,...,...,...,...,...,...,...
72,الومنيوم,شريط الومنيوم 3 متر,محلى,إكسسوارات,40*4,20,مقطع,-,20,متاح
73,الومنيوم,شريط الومنيوم 3 متر,محلى,إكسسوارات,40*3.25,148,المقاسات غير دقيقة DT,-,148,متاح
74,الومنيوم,شريط الومنيوم 3 متر,محلى,إكسسوارات,60*4,138,المقاسات غير دقيقة DT,-,138,متاح
75,الومنيوم,شريط الومنيوم 3 متر,محلى,إكسسوارات,60*3.25,111,المقاسات غير دقيقة DT,-,111,متاح
76,الومنيوم,مجموعة الومنيوم مفكوكة من بارات اليكس ويست بار...,محلى,إكسسوارات,60*3.25,0,المقاسات غير دقيقة DT,-,0,غير متاح

In [62]:
fig3 = px.treemap(df,path=['مقاس'],template='simple_white',color_discrete_sequence=['#0F52BA'])

fig3.update_traces(
    hovertemplate=
    "<b>%{label}</b><br>" +
    "Count: %{value}<br>"
)

fig3 = apply_figure_layout(fig3)
fig3